name = "Verlet"
uuid = "ceff7d4a-2a53-480e-a497-2b53b48090dd"
authors = ["Ilian Pihlajamaa <ilian.pihlajamaa@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
